name = "ruouohninhbinh-shop"
type = "service"
main = "src/index.ts"
compatibility_date = "2024-12-30"

[[d1_databases]]
binding = "DB"
database_name = "ruouohninhbinh-db"
database_id = "80af41bc-6f76-44a5-95ad-5f558c028f64"

[vars]
CURRENCY = "vnd"
STORE_NAME = "Rượu Ó Ninh Bình"
